using Oscar
function collect_examples(oscardir::String)
    booktestdir = joinpath(oscardir, "test/book")
    examples = load(joinpath(booktestdir, "ordered_examples.json"))
    for key in keys(examples)
        println(key)
        folder, filename = split(key, "/")
        if !isdir(joinpath(".", folder))
            mkdir(joinpath(".", folder))
        end
        entire = read(joinpath("../examples_templates", folder, filename*".md"), String)
        output = String(entire)
        println(entire)
        for m in eachmatch(r"# INSERT_EXAMPLE (\S*)", entire)
            codefile = m[1]
            code = read(joinpath(booktestdir, codefile), String)
            println(codefile)
            if !endswith(code, "\n")
                code *= "\n"
            end
            output = replace(output, Regex("# INSERT_EXAMPLE $codefile\n")=>code)
        end
        println(output)
        io = open(joinpath("../examples_autogenerated", folder, filename*".md"), "w")
        write(io, output)
        close(io)
    end
end
