using Pkg
Pkg.add("HTTP")
Pkg.add("JSON")
Pkg.add("YAML")

using HTTP
using JSON
using YAML

# fetch latest version

releaseURL = "https://api.github.com/repos/oscar-system/oscar.jl/releases/latest"
r = HTTP.request("GET", releaseURL)
if r.status != 200
    error("Network error when trying to fetch latest version!")
end
latestVersion = JSON.parse(r.body)["name"]

major, minor, patch = split(latestVersion, ".")
major, minor, patch = parse.(Int, [major[2:end], minor, patch])

# build the list of versions
# as long as its Oscar 1.x, we can get away with using a single loop
# when we hit Oscar 2.x, we will need a double loop

versions = []

for i in minor:-1:0
    push!(versions, "1.$i")
end

# write versions to file
YAML.write_file("../_data/versions.yml", versions)
println("Making cache path for downloads")
cachepath = joinpath(".","cache")
mkpath(cachepath)

for version in versions

    # debug output for now, to be cleaned up once we trust the script
    println("Making temp directory for $(version)")
    mytmpdir = mktempdir(; prefix="book_$(version)")

    if version == "1.0"
        zipurl = "https://api.github.com/repos/oscar-system/Oscar.jl/zipball/v$(version).1"
    else
        zipurl = "https://api.github.com/repos/oscar-system/Oscar.jl/zipball/v$(version).0"
    end

    # download latest zip
    println("Grabbing latest Oscar release information")
    local r = HTTP.request("HEAD", zipurl)
    if r.status != 200
        error("Network issue when fetching OSCAR zips!")
    end
    dlfilename = ""
    for (k,v) in r.headers
        if k == "content-disposition"
            index = findfirst("filename=", v).stop
            dlfilename = v[index+1:end]
            break
        end
    end
    dlpath = joinpath(cachepath, dlfilename)
    if !isfile(dlpath)
        # do the actual download only if not already in cache
        println("Version $(version) not found in cache! Downloading...")
        r = HTTP.request("GET", zipurl)
        d = open(dlpath, "w")
        write(d, r.body)
    else
        println("Version $(version) found in cache! Reusing...")
    end

    println("Copying file to tmpdir...")
    finalpath = joinpath(mytmpdir, "dl.zip")
    cp(dlpath, finalpath)

    # unzip
    println("Inflating content")
    owd = pwd()
    cd(mytmpdir)
    run(`unzip dl.zip`)
    oscardir = joinpath(mytmpdir,filter(x -> occursin("oscar", x), readdir("./"))[1])
    cd(owd)
    mkpath("../$(version)/examples_autogenerated")

    # we trust everything after this

    function collect_examples(oscardir::String)
        booktestdir = joinpath(oscardir, "test/book")
        examples = JSON.parse(open(joinpath(booktestdir, "ordered_examples.json")))["data"]
        for key in keys(examples)
            println(key)
            folder, filename = split(key, "/")
            if !isdir(joinpath("..", version, "examples_autogenerated", folder))
                mkdir(joinpath("..", version, "examples_autogenerated", folder))
            end
            entire = read(joinpath("../examples_templates", folder, filename*".md"), String)
            output = String(entire)
            println(entire)
            # get rid of permalink and redirect layout
            output = replace(output, "layout: redirect" => "layout: page")
            output = replace(output, r"permalink: .*" => "")
            for m in eachmatch(r"# INSERT_EXAMPLE (\S*)", entire)
                codefile = m[1]
                try
                    code = read(joinpath(booktestdir, codefile), String)
                catch
                    try
                        codefile = replace(codefile, "jlcon" => "jl")
                        code = read(joinpath(booktestdir, codefile), String)
                    catch
                        println(codefile)
                        error("file not found")
                    end
                end
                code = split(code, "# output")[1]
                println(codefile)
                if !endswith(code, "\n")
                    code *= "\n"
                end
                output = replace(output, Regex("# INSERT_EXAMPLE $codefile\n")=>code)
            end
            println(output)
            io = open(joinpath("../$(version)/examples_autogenerated", folder, filename*".md"), "w")
            write(io, output)
            close(io)
        end
    end

    collect_examples(oscardir)
end
